// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.throttle.version", 1);
user_pref("app.normandy.startupRolloutPrefs.layout.display-list.retain", true);
user_pref("app.normandy.user_id", "29058a3f-d86b-4a7e-aa64-17fe42c1847c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1531845461);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1531845615);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1531845101);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1531845341);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1531845869);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1531845221);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1531845071);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a295e88a-427e-4d3f-9943-1ef35a1044ce}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1531778400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1531845586);
user_pref("browser.onboarding.notification.prompt-count", 2);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\",\"addSearchEngine\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1531845135107");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1531846929107");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1531845075978");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1531848675978");
user_pref("browser.search.countryCode", "IT");
user_pref("browser.search.region", "IT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180704194937");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1531845840");
user_pref("browser.slowStartup.averageTime", 2092);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180704194937");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.matchBuckets", "general:5,suggestion:Infinity");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1531845073850");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1531845462);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180208175058");
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"b215c6f4-4605-41ba-a57e-f0618601e43c\",\"webcompat@mozilla.org\":\"b157eb83-6b5d-4bfe-a47b-6e62693f18a3\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("gecko.handlerService.migrated", true);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1531845181);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180208175058");
user_pref("media.gmp-manager.lastCheck", 1531845181);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.throttle.version", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f2cf8d9e-22b2-4b01-9055-69a015b95369");
user_pref("services.blocklist.addons.checked", 1531763929);
user_pref("services.blocklist.clock_skew_seconds", 81686);
user_pref("services.blocklist.gfx.checked", 1531763929);
user_pref("services.blocklist.last_etag", "\"1531762863373\"");
user_pref("services.blocklist.last_update_seconds", 1531763929);
user_pref("services.blocklist.onecrl.checked", 1531763929);
user_pref("services.blocklist.pinning.checked", 1531763929);
user_pref("services.blocklist.plugins.checked", 1531763929);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1531845837);
user_pref("toolkit.telemetry.cachedClientID", "f0f3d3a7-2b0a-45c5-af6a-35b4c876d3e7");
user_pref("toolkit.telemetry.previousBuildID", "20180704194937");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
